### ISSUE TITLE
Open File not worked

### ISSUE THREAD

**Issue by varlesh** [Zren/mpvz#7]
**Open - File**  on right click mouse menu not worked . Hotkey (Ctrl+F) too
Builded from master branch, current git-version 

log
```
alex@alex:~$ mpvz
qrc:/qml/MpvPlayer.qml:477:3: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/MpvPlayer.qml:451:4: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/VolumeSlider.qml:20:2: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/SeekbarSlider.qml:18:2: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/SeekbarSlider.qml:150:6: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qml/MpvPlayer.qml:40:31: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
```
Operating System: KDE neon 5.22
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.3
Kernel Version: 5.13.0-10.2-liquorix-amd64 (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i5-10400F CPU @ 2.90GHz
Memory: 7.7 ГиБ of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by varlesh** [comment]
File fine opening from Dolphin, but on menu player Open - File nothing happens

**Comment by varlesh** [comment]
ouh, it's not implemented yet:
https://github.com/Zren/mpvz/blob/master/src/qml/AppActions.qml#L10

**Comment by Zren** [comment]
I think I left it for later since I didn't know all the file extensions. Turns out it was more annoying than I thought since I needed a qt `widgets` import for qt to use the native file picker. Looks like it now also uses native contextmenus too.

**Comment by varlesh** [comment]
worked now, thx
